### PR TITLE
Update Hugo to v0.17

### PR DESCRIPTION
**Pull request by solidnerd**
Hey,
I like your concept of deployment for hugo blog. So I tried it for my self and it works flawlessy. I want to contribute something back. So I updated Hugo to the latest stable version.

### CODE REVIEW

**Comment by StefanScherer** [comment]
Hey @solidnerd thank you! But it seems we have some issues with our themes as CircleCI is red.

**Comment by solidnerd** [comment]
I could fix it :)

**Comment by StefanScherer** [comment]
@solidnerd Sorry for the delay. Just tried it locally with Hugo 0.18.0. Thanks!

**Comment by DieterReuter** [comment]
@solidnerd cool, our blog works with latest Hugo now, thanks!

**Pull request merged**
